# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool: myagent

steps:
    - task: InstallShieldBuild@1
      inputs:
        PrjName: 'C:\Users\admin\Desktop\devopstestproject\testdevops.ism'
        Parameters: '-v -r "IS-RELEASE" -l PATH_TO_INSTALLATIONS_FILES="$(build.artifactstagingdirectory)\Drop" -y "1.2.33"'
        AgentLoc: 'PrivateAgent'
        SABPath: 'C:\Program Files (x86)\InstallShield\2023 SAB'
